<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Workshop-4" data-toc-modified-id="Workshop-4-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Workshop 4</a></span><ul class="toc-item"><li><span><a href="#ESERCIZIO-2" data-toc-modified-id="ESERCIZIO-2-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>ESERCIZIO 2</a></span></li><li><span><a href="#ESERCIZIO-3" data-toc-modified-id="ESERCIZIO-3-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>ESERCIZIO 3</a></span></li><li><span><a href="#ESERCIZIO-4" data-toc-modified-id="ESERCIZIO-4-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>ESERCIZIO 4</a></span></li><li><span><a href="#ESERCIZIO-5" data-toc-modified-id="ESERCIZIO-5-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>ESERCIZIO 5</a></span></li></ul></li></ul></div>

# Workshop 4

**Svolgi i seguenti esercizi in Python:**

**1.** Crea una matrice 3x3 con valori compresi tra 0 e 8

**2.** Crea un vettore random con 30 elementi e trova il valore medio

**3.** Trova gli indici degli elementi diversi da zero del seguente array [3,5,0,4,0,8,0]

**4.** Scrivi un programma per ottenere gli indici degli elementi ordinati di un dato array ,esempio :

    array: [1023 5202 6230 1671 1682 5241 4532] indice degli elementi ordinati dell'array :[0 3 4 6 1 5 2]

**5.** Scrivi un programma che calcola la media attraverso la dimensione, in un array 2D ,esempio :

    array: [[10 30]

    [20 60]]

    media di ogni colonna: [15 45]

    media di ogni riga: [20 40]


In [3]:
import numpy as np
import random as rnd
from scipy import stats

In [64]:
#Crea una matrice 3x3 con valori compresi tra 0 e 8
matrice3x3=np.arange(0,9).reshape(3,3)
matrice3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
vettorerandom2=np.array([rnd.randint(0,100) for i in range(30)])
vettorerandom2

array([53, 33, 58, 96, 95,  1, 15, 83,  4, 25, 16, 72, 48, 53, 69, 27, 75,
        6, 82, 30, 15, 31, 37, 85, 93, 81, 44, 35, 91, 35])

In [65]:
#Crea un vettore random con 30 elementi e trova il valore medio
vettorerandom=np.random.randint(0, high=100, size=30)
vettorerandom

array([97, 38, 56, 66, 83,  3, 87, 27, 10, 51, 56, 66, 47, 81, 19,  1, 53,
       83, 16, 61, 12, 81, 93, 65, 49, 45,  7, 75, 32, 89])

In [9]:
np.mean(vettorerandom)

49.86666666666667

In [66]:
#Trova gli indici degli elementi diversi da zero del seguente array [3,5,0,4,0,8,0]
array1= np.array([3,5,0,4,0,8,0])
def trovadivdazero(array_):
    listaindici=[i for i in range(len(array_)) if array_[i] != 0]
    return listaindici

trovadivdazero(array1)
    


[0, 1, 3, 5]

In [16]:
list(enumerate(array1))

[(0, 3), (1, 5), (2, 0), (3, 4), (4, 0), (5, 8), (6, 0)]

In [67]:
#versione con enumerate
array2= np.array([3,5,0,4,0,8,0])
def trovadivdazero2(array_):
    listaindici=[i for (i, j) in enumerate(array_) if j != 0]
    return listaindici

trovadivdazero2(array2)
    

[0, 1, 3, 5]

In [68]:
#Scrivi un programma per ottenere gli indici degli elementi ordinati di un dato array
array3= np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
arrayordinato=list(enumerate(sorted(array3)))
arrayordinato

[(0, 1023), (1, 1671), (2, 1682), (3, 4532), (4, 5202), (5, 5241), (6, 6230)]

In [27]:
def indiciordinati(array_):
    arrayordinato=sorted(array_)
    listaindiciordinati=[]
    for i in arrayordinato:
         for (j,k) in enumerate(array_):
                if k == i:
                    listaindiciordinati.append(j)
    return listaindiciordinati

indiciordinati(array3)
            
    

[0, 3, 4, 6, 1, 5, 2]

In [63]:
def indiciordinati2(array_): #versione con doppio for nella list comprehension
    arrayordinato=sorted(array_)
    listaindiciordinati=[j for i in arrayordinato for (j,k) in enumerate(array_) if k == i]
    return listaindiciordinati

indiciordinati2(array3)

[0, 3, 4, 6, 1, 5, 2]

Scrivi un programma che calcola la media attraverso la dimensione, in un array 2D 
array4= np.array([[10, 30],
[20, 60]])
array4

In [4]:
array4= np.array([[10, 30], [20, 60]])
array4[0,:]

array([10, 30])

In [10]:
array4.shape[0] 

2

In [62]:
def funzioneimpossibile(matrice):
    mediarighe=[np.mean(matrice[i,:],dtype=int) for i in range(matrice.shape[0])]
    mediacolonne=[np.mean(matrice[:,j],dtype=int) for j in range(matrice.shape[1])]
    print(f'media di ogni colonna: {mediacolonne}')
    print(f'media di ogni riga: {mediarighe}')
funzioneimpossibile(array4)

media di ogni colonna: [15, 45]
media di ogni riga: [20, 40]
